version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: login-app
        LoadBalancerInfo:
          ContainerName: "ecs_s"
          ContainerPort: 5000
